
import {
  Home,
  BookAudio,
  Sunrise,
  Sparkles,
  TrendingUp,
  BookOpen,
  KeyRound,
  ShieldQuestion,
  Library,
  ClipboardCheck,
  Shapes,
  Compass,
  Youtube,
  Feather,
  CheckCircle,
  HeartHandshake,
  Headphones,
  Users,
  Mic,
  Star,
  Clock,
  Orbit,
  LineChart,
  Dices,
  ShieldOff,
  Recycle,
} from 'lucide-react';

export const navItems = [
  { href: '/', label: 'ಮುಖಪುಟ', icon: Home },
  { href: '/tour', label: 'ಸೈಟ್ ಪ್ರವಾಸ', icon: Compass },
  { href: '/sadhana', label: 'ನಿತ್ಯ ಸಾಧನಾ', icon: Sunrise },
  { href: '/initiation', label: 'ದೀಕ್ಷೆ', icon: KeyRound },
  { href: '/guidance', label: 'ಮಾರ್ಗದರ್ಶನ', icon: ShieldQuestion },
  { href: '/astrology', label: 'ಜ್ಯೋತಿಷ್ಯ', icon: Star },
  { href: '/kaalagnana', label: 'ಕಾಲಜ್ಞಾನ', icon: Clock },
  { href: '/karma-rahasya', label: 'ಕರ್ಮ ರಹಸ್ಯ', icon: Orbit },
  { href: '/shatkriya-rahasya', label: 'ಷಟ್ಕ್ರಿಯಾ ರಹಸ್ಯ', icon: Recycle },
  { href: '/shatkarma-rahasya', label: 'ಷಟ್ಕರ್ಮ ರಹಸ್ಯ', icon: Recycle },
  { href: '/share-market-astrology', label: 'ಶೇರು ಮಾರುಕಟ್ಟೆ ಜ್ಯೋತಿಷ್ಯ', icon: LineChart },
  { href: '/gambling', label: 'ಜೂಜು ಮತ್ತು ಅದೃಷ್ಟ', icon: Dices },
  { href: '/black-magic', label: 'ಮಾಟ ಮಂತ್ರ', icon: ShieldOff },
  { href: '/yantras', label: 'ಯಂತ್ರಗಳು', icon: Shapes },
  { href: '/mantras', label: 'ಮಂತ್ರಗಳು', icon: BookAudio },
  { href: '/activities', label: 'ಚಟುವಟಿಕೆಗಳು', icon: CheckCircle },
  { href: '/remedies', label: 'ಪರಿಹಾರಗಳು', icon: HeartHandshake },
  { href: '/recommendations', label: 'ಶಿಫಾರಸುಗಳು', icon: Sparkles },
  { href: '/articles', label: 'ಲೇಖನಗಳು', icon: Feather },
  { href: '/audio', label: 'ಆಡಿಯೋ ಲೈಬ್ರರಿ', icon: Headphones },
  { href: '/mantra-generator', label: 'ಮಂತ್ರ ಆಡಿಯೋ', icon: Mic },
  { href: '/knowledge', label: 'ಜ್ಞಾನ', icon: BookOpen },
  { href: '/literature', label: 'ಸಾಹಿತ್ಯ', icon: Library },
  { href: '/duties', label: 'ಸಾಧಕನ ಕರ್ತವ್ಯಗಳು', icon: ClipboardCheck },
  { href: '/progress', label: 'ಪ್ರಗತಿ', icon: TrendingUp },
  { href: '/forum', label: 'ಸಮುದಾಯ ವೇದಿಕೆ', icon: Users },
  { href: '/youtube', label: 'YouTube', icon: Youtube },
];
